name: MultiOS

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest MSVC 2019",
            os: windows-2019,
            build_type: "Release",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
          - {
            name: "Ubuntu Latest",
            os: ubuntu-latest,
            build_type: "Release"
          }
          - {
            name: "macOS 10.15",
            os: macos-10.15,
            build_type: "Release"
          }

    steps:
      - uses: actions/checkout@v2
      #- name: fetchtags
      #  run: git fetch --unshallow --tags
      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
      - name: Build with CMake
        run: cmake --build build --config ${{ matrix.config.build_type }}